name: Vulnerability Scain (Trivy)

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-18.04
    steps:
      - name: Pull docker image
        run: docker pull ghcr.io/marlluslustosa/onionize-docker:latest

      - uses: homoluctus/gitrivy@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: ghcr.io/marlluslustosa/onionize-docker:latest
