name: Vulnerability Scain (Trivy)

#on:
#  schedule:
#    - cron: '0 9 * * *'

on:
  push:
    branches:
      - master

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-18.04
    steps:
      - name: Pull docker image
        run: docker pull imega/mariadb-client

      - uses: homoluctus/gitrivy@v1.0.0
        id: trivy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: imega/mariadb-client
      
      - uses: nick-invision/persist-action-data@v1
        with:
          data: ${{ steps.trivy.outputs.html_url }}
          variable: html_url
      
      - name: print url html issue
        run: |
          echo ${{steps.trivy.outputs.html_url}}
          echo ::set-output name=link::${{ steps.trivy.outputs.html_url }}

  jobinho:
    runs-on: ubuntu-18.04
    needs: scan
    steps:
      - uses: nick-invision/persist-action-data@v1
        id: global-data
        with:
          data: ${{ steps.trivy.outputs.html_url }}
          retrieve_variables: html_url
      
      - run: |
          echo ${{ steps.global-data.outputs.html_url }}
          echo ${{ html_url }}
      
      - name: step condicional
        if: ${{ steps.global-data.outputs.html_url == "https://github.com/marlluslustosa/onionize-docker/issues/12" }}
        run: echo Deu certo a condicao do step
