name: Vulnerability Scain (Trivy)

#on:
#  schedule:
#    - cron: '0 9 * * *'

on:
  push:
    branches:
      - master

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-18.04
    steps:
      - name: Pull docker image
        run: docker pull imega/mariadb-client

      - uses: homoluctus/gitrivy@v1.0.0
        id: trivy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: imega/mariadb-client

  job2:
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: print url html issue 
        run: echo ${{ needs.scan.steps.trivy.outputs.html_url }}
