name: Vulnerability Scain (Trivy)

#on:
#  schedule:
#    - cron: '0 9 * * *'

on:
  push:
    branches:
      - master

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-18.04
    steps:
      - name: Pull docker image
        run: docker pull imega/mariadb-client

      - uses: homoluctus/gitrivy@v1.0.0
        id: trivy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: imega/mariadb-client

      - name: print url html issue
        run: |
          echo ${{steps.trivy.outputs.html_url}}
          echo ::set-output name=link::${{ steps.trivy.outputs.html_url }}

  jobinho:
    runs-on: ubuntu-18.04
    needs: scan
    steps:
      #      - name: print url html issue 
    - run: |
        echo "${{ needs.scan.steps.trivy.outputs.html_url }}"
        echo "${{ needs.scan.steps.trivy.outputs.link }}"
